# Generated by Django 5.2.6 on 2025-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, default='No excerpt'),
            preserve_default=False,
        ),
    ]
