# Generated by Django 5.2.6 on 2025-09-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    migrations.CreateModel(
        name='About',
        fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ('title', models.CharField(max_length=200)),
            ('updated_on', models.DateTimeField(auto_now=True)),
            ('content', models.TextField()),
        ],
    ),
]
